#!/bin/bash
# Expected environment variables
# * role (first part of the hostname)
# * instance (second part of the hostname)
# * gitcmdb_path (folder where repo was downloaded)
echo Running puppet installer

# check if puppet is installed
if [ -z $(which puppet) ]; then
  if [ -e /etc/redhat-release ]; then
      if [ -z "$(grep -i centos /etc/redhat-release)" ]; then
          yum install -y epel-release
      fi
    yum -y install puppet
  elif [ -e /etc/debian_version ]; then
    apt-get -y install puppet
  elif [ -e /etc/system-release ]; then
    yum -y install puppet
  else
     echo "Unsuported distribution"
     return 1
  fi
fi

#check if r10k is installed
if [ -z $(which r10k) ]; then
  gem install r10k
fi

# check /etc/puppet link
if [ ! "$(readlink /etc/puppet)" = "$gitcmdb_path/gitcmdb_installer/puppet" ]; then
  mv -f /etc/puppet /etc/puppet.`date +%s`
  ln -sf $gitcmdb_path/gitcmdb_installer/puppet /etc/puppet
fi

# check /etc/facter/facts.d link
mkdir -p /etc/facter
if [ ! "$(readlink /etc/facter/facts.d)" = "$gitcmdb_path/gitcmdb_installer/puppet/facts.d" ]; then
  mv -f /etc/facter/facts.d /etc/facter/facts.d.`date +%s`
  ln -sf $gitcmdb_path/gitcmdb_installer/puppet/facts.d /etc/facter/facts.d
fi

# install Puppetfile modules
if [ -e /etc/puppet/Puppetfile -a -e /etc/puppet/modules ]; then
  r10k puppetfile install --puppetfile /etc/puppet/Puppetfile --moduledir /etc/puppet/puppetfile-modules
fi

# run puppet
if [ -e /etc/puppet/manifests/site.pp ]; then
  puppet apply --modulepath /etc/puppet/modules:/etc/puppet/puppetfile-modules /etc/puppet/manifests/site.pp
else
  echo "File /etc/puppet/manifests/site.pp does not exist"
fi
